spring.application.name=taskbridge-api
spring.jpa.hibernate.ddl-auto=update
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
app.security.jwt.secret=${APP_JWT_SECRET:}
app.security.jwt.lifetime=${APP_JWT_LIFETIME:PT15M}
app.security.bootstrap.enabled=${APP_BOOTSTRAP_USER_ENABLED:false}
app.security.bootstrap.username=${APP_BOOTSTRAP_USER_USERNAME:}
app.security.bootstrap.password=${APP_BOOTSTRAP_USER_PASSWORD:}
app.security.bootstrap.organisation-id=${APP_BOOTSTRAP_USER_ORGANISATION_ID:}
app.security.bootstrap.authorities=${APP_BOOTSTRAP_USER_AUTHORITIES:project:read,project:create,project:update,project:delete}
app.web.allowed-origins=${APP_WEB_ALLOWED_ORIGINS:http://localhost:4200}
